# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "invenio.box"
  config.vm.network "private_network", ip: "192.168.33.3"
  config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", 2]
  end

  config.vm.provision "shell", path: "../provision-puppet.sh"

  config.vm.provision "puppet" do |puppet|
    puppet.options = "--verbose"
    puppet.manifest_file = "site-ils.pp"
    puppet.manifests_path = "../manifests/"
    puppet.module_path = "../modules/"
  end
end
